### ISSUE TITLE
Student Management System - Style Signup and Login Page

### ISSUE THREAD

**Issue by mirasoldavila13** [bhanusreek85/StudentRepositorySystem#10]
## User Story:

AS A developer
I WANT TO style the signup and login page using CSS
SO THAT the page looks visually appealing and matches the design specifications

## Acceptance Criteria:

1. The signup and login page should be styled using CSS.
2. The styling should match the design specifications.

## Tasks:

- [x] Apply Tailwind CSS to the signup and login page
- [x] Ensure the styles match the approved design
- [x] Review and approve the CSS Styles with the team
