### ISSUE TITLE
Student Management System - Test Signup and Login Functionality Using Local Storage

### ISSUE THREAD

**Issue by mirasoldavila13** [bhanusreek85/StudentRepositorySystem#15]
## User Story:

AS A developer
I WANT TO test the signup and login functionality using local storage
SO THAT I can ensure the processes work correctly and securely

## Acceptance Criteria:

1. Unit tests for the signup and login functionality should be written and passed.
2. End-to-end testing should ensure the signup and login processes work seamlessly.

## Tasks:

- [x] Write unit tests for the signup functionality.
- [x] Write unit tests for the login functionality.
- [x] Perform end-to-end testing for signup and login processes.
- [x] Review and approve test results with the team.
