### ISSUE TITLE
Student Management System - Implement Login Page Structure

### ISSUE THREAD

**Issue by mirasoldavila13** [bhanusreek85/StudentRepositorySystem#8]
## User Story:

AS A teacher
I WANT TO implement the HTML structure for the login page
SO THAT I can create the basic layout for the user interface

## Acceptance Criteria:

1. The HTML structure for the signup and login page should be implemented according to the design.

## Tasks:

- [x] 1. Implement the HTML structure for the signup and login page.
- [x] 2. Ensure the structure matches the approved design.
- [x] 3. Review and approve the HTML structure with the team.
